pypro/base/urls.py
from django.urls import path
from pypro.base.views import home

app_name = "base"
urlpatterns = [
    path("", home, name="home"),
]

pypro/modulos/urls.py
from django.urls import path
from pypro.modulos import views


app_name = "modulos"
urlpatterns = [
    path("", views.indice, name="indice"),
    path("<slug:modulo_slug>", views.detalhe, name="detalhe"),
    path("aulas/<slug:aula_slug>", views.aula, name="aula")
]

pypro/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contas/", include("django.contrib.auth.urls")),
    path("", include("pypro.base.urls")),
    path("aperitivos/", include("pypro.aperitivos.urls")),
    path("modulos/", include("pypro.modulos.urls")),
    path("turmas/", include("pypro.turmas.urls")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

pypro/modulos/models.py
from django.db import models
from django.urls import reverse
from ordered_model.models import OrderedModel


class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)

    def __str__(self) -> str:
        return self.titulo

    def get_absolute_url(self) -> str:
        return reverse("modulos:detalhe", args=(self.slug,))


class Aula(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey("Modulo", on_delete=models.PROTECT)
    order_with_respect_to = "modulo"
    vimeo_id = models.CharField(max_length=32)

    class Meta:
        ordering = ("modulo", "order")

    def __str__(self) -> str:
        return self.titulo

    def get_absolute_url(self) -> str:
        return reverse("modulos:aula", args=(self.slug,))

pypro/modulos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from pypro.modulos import facade


def indice(request):
    modulos = facade.listar_modulos_com_aulas()
    return render(request, "modulos/indice.html", context={"modulos": modulos})


def detalhe(request, modulo_slug):
    modulo = facade.buscar_modulo(modulo_slug)
    aulas = facade.listar_aulas_do_modulo_ordenadas(modulo)
    return render(request, "modulos/detalhe.html", context={"modulo": modulo, "aulas": aulas})


@login_required
def aula(request, aula_slug):
    aula = facade.buscar_aula(aula_slug)
    return render(request, "modulos/aula_detalhe.html", context={"aula": aula})

pypro/modulos/templates/modulos/aula_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block description %}Página com detalhes da aula {{ aula.titulo }}{% endblock description %}
{% block styles %}<link href="{% static 'css/videos.css' %}" rel="stylesheet" />{% endblock styles %}
{% block title %}Python Pro - {{ aula.titulo }}{% endblock title %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'base:home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ aula.modulo.get_absolute_url }}">{{ aula.modulo.titulo }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ aula.titulo }}</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col">
            <div class="container rounded mt-4 mb-3">
                <h1 class="h1">{{ aula.modulo }} - {{ aula.titulo | default:'Faltando título da aula' }}</h1>
                <div class="video-container">
                    <iframe src="https://player.vimeo.com/video/{{ aula.vimeo_id }}?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                            frameborder="0"
                            allow="autoplay; fullscreen; picture-in-picture"
                            class="video-frame">
                    </iframe>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}
{% block scripts %}
    <script src="https://player.vimeo.com/api/player.js"></script>
{% endblock scripts %}

pypro/modulos/templates/modulos/detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block description %}Página com detalhes do módulo {{ modulo.titulo }}{% endblock description %}
{% block title %}{{ modulo.titulo }}{% endblock title %}
{% block body %}
<div class="row">
    <div class="col">
        <div class="container rounded mt-4 mb-3">
            <h1 class="h1">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público</dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição</dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2 class="h2">Aulas</h2>
            <ol class="list-group list-group-flush">
                {% for aula in aulas %}
                <li class="list-group-item">{{ forloop.counter }}. <a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                {% empty %}
                <li class="list-group-item list-group-item-warning">Nenhuma aula cadastrada</li>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock body %}

pypro/modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block description %}Página com lista de módulos{% endblock description %}
{% block title %}Módulos{% endblock title %}
{% block body %}
<div class="row">
    <div class="col">
        <div class="container rounded mt-4 mb-3">
            <h1 class="h1">Módulos</h1>
            <ol class="list-group">
                {% for modulo in modulos %}
                <li class="list-group-item list-group-item-action list-group-item-primary"><a href="{{ modulo.get_absolute_url }}">{{ modulo.titulo }}</a></li>
                <dl>
                    <dt>Público</dt>
                    <dd>{{ modulo.publico }}</dd>
                    <dt>Descrição</dt>
                    <dd>{{ modulo.descricao }}</dd>
                    <dt>Aulas</dt>
                    <dd>
                        <ol>
                            {% for aula in modulo.aulas %}
                            <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                            {% empty %}
                            <li class="list-group-item list-group-item-warning">Nenhuma aula cadastrada</li>
                            {% endfor %}
                        </ol>
                    </dd>
                </dl>
                <hr />
                {% empty %}
                <li class="list-group-item list-group-item-warning">Nenhum módulo cadastrado</li>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock body %}